### ISSUE TITLE
errors when printing

### ISSUE THREAD

**Issue by ABoehm4** [CSIS221Longview/AdamBattle#1]
I'm not far into this at all. I can't even get the darn board to print some values. I tried initializing the board to '~'
```
private void fillboard() {
	// initializing both the board and ship array to -1
	for(int i = 0; i < this.BOARD_SIZE; i++) {
		for (int j = 0; j < this.BOARD_SIZE; j++) {
			ships[i][j] = '~';
			board[i][j] = '~';
		}
	}
}



public void printboard() {
	// for printing the top column of the game board going to the right
	System.out.print("\n   ");
	for (int i = 0; i < this.BOARD_SIZE; i++) {
		System.out.printf("%3d", i+1);	
	}
	// start of main loop for printing the rows for the rest of the board
	// for printing the numbers (converted to letters) going down
	for (int i = 0; i < this.BOARD_SIZE; i++) {
		System.out.print("\n");
		System.out.printf("%3c", getLetter(i+1));
		for (int j = 0; j < this.BOARD_SIZE; j++) {
			System.out.printf("%3c", board[i][j]);	
            }
            
        }
}
```
then printing it but I keep getting errors. Not really sure how to fix this one. 

  AException in thread "main" java.lang.NullPointerException
	at battleship.gameboard.printboard(gameboard.java:43)
	at battleship.battleship.main(battleship.java:39)

**Comment by ABoehm4** [comment]
That code link really comes out ugly on this site.

**Comment by ABoehm4** [comment]
gameboard.java http://paste.ofcode.org/vGQamfaN9EyWim3HEBQEsy
battleship.java http://paste.ofcode.org/Pn8iDQyyKpA8BpVmJZqkiX

Another way of looking at all the code.

**Comment by Sheldon93** [comment]
Did you make a constructor for gameboard.java? I've been trying to create my gameboard.java object in my battleship.java file or even my actiongame.java file but I keep having to pass all parameters through the constructor for example: gameboard board = new gameboard(int[] SHIPS, String[][] beginner, String[][] standard, String[][] advanced) in the other files but still getting errors on my end trying to do that, as well.

**Comment by Sheldon93** [comment]
Just out of curiosity, is it giving you any problems in your battleship.java file when you create your board object statically? Maybe that's what my problem is. I noticed you didn't use parameters and I was just curious as to why I keep getting errors trying to create my gameboard object from my other files.

**Comment by ABoehm4** [comment]
So far, I'm getting no errors in my battleship.java file. The only error I receive is when I try to 
`System.out.printf("%3c", board[i][j]);` 
It comes back with 

```
You have three difficulties to choose from
   LEVEL        BOARD SIZE        MISSLES
1. Beginner        6x6               30   
2. Standard        9x9               50   
3. Advanced       12x12              75   
Select your board size by entering the number 1, 2, or 3:  2

You have chosen Standard. Just average eh?

Board size is: 9x9

     1  2  3  4  5  6  7  8  9
  AException in thread "main" java.lang.NullPointerException
	at battleship.gameboard.printboard(gameboard.java:43)
	at battleship.battleship.main(battleship.java:39)

```

**Comment by ABoehm4** [comment]
If I take out that one line of code and run it again, it comes out as
```
You have three difficulties to choose from
   LEVEL        BOARD SIZE        MISSLES
1. Beginner        6x6               30   
2. Standard        9x9               50   
3. Advanced       12x12              75   
Select your board size by entering the number 1, 2, or 3:  2

You have chosen Standard. Just average eh?

Board size is: 9x9

     1  2  3  4  5  6  7  8  9
  A
  B
  C
  D
  E
  F
  G
  H
  I
```

**Comment by Sheldon93** [comment]
What happens if you try to call your fillboard() method in your printboard() method?

**Comment by ABoehm4** [comment]
I switched fillboard() from setboard() to printboard() and getting these new errors below.

```
You have three difficulties to choose from
   LEVEL        BOARD SIZE        MISSLES
1. Beginner        6x6               30   
2. Standard        9x9               50   
3. Advanced       12x12              75   
Select your board size by entering the number 1, 2, or 3:  3

You have chosen Advanced. You must be confident!
Exception in thread "main" java.lang.NullPointerException
	at battleship.gameboard.fillboard(gameboard.java:22)
	at battleship.gameboard.printboard(gameboard.java:30)
	at battleship.battleship.main(battleship.java:39)

```

points at my `board[i][j] = '~';` being messed up now. I'm pretty lost at trying to figure this out.

**Comment by ABoehm4** [comment]
So I used `System.out.println(Arrays.toString(board));` to force a print out of whatever is loaded into the array and it's all coming out null value. My fillboard() is not actually loading '~' into any of the array.
```
private void fillboard() {
	// initializing both the board and ship array to ~
	for(int i = 0; i < this.BOARD_SIZE; i++) {
		for (int j = 0; j < this.BOARD_SIZE; j++) {
			board[i][j] = '~';
		}
	}
}
```

**Comment by ABoehm4** [comment]
I figured out my issue for basic printing of the board. I never actually called setboard() so it never called fillboard();

My code now looks like 
```
You have three difficulties to choose from
   LEVEL        BOARD SIZE        MISSLES
1. Beginner        6x6               30   
2. Standard        9x9               50   
3. Advanced       12x12              75   
Select your board size by entering the number 1, 2, or 3:  1

You have chosen beginner. You must be scared.

Board size is: 6x6

    1  2  3  4  5  6
  A ~| ~| ~| ~| ~| ~|
  B ~| ~| ~| ~| ~| ~|
  C ~| ~| ~| ~| ~| ~|
  D ~| ~| ~| ~| ~| ~|
  E ~| ~| ~| ~| ~| ~|
  F ~| ~| ~| ~| ~| ~|
```

**Comment by JosephCW** [comment]
The way I pretty much did it was something like this..

// For every position on the board it will check to see if there was a ship there. Then if there isn't it will set it to be the character version of the ship. (A for aircraft carrier, S for submarine, etc.)

    for (int i = 0; i < MAX_BOARD_SIZE; i++) {
        for(int j = 0; j < MAX_BOARD_SIZE; j++) {
            if (shipAtPosition(x, y) {
                board[i][j] = getShipAtPosition(x, y).getCharacterVersion();       
            } else {
                board[i][j] = "~";
            }
        }
    }
